### ISSUE TITLE
cannot load such file -- browsermob/proxy

### ISSUE THREAD

**Issue by samnissen** [Shashikant86/browsermob-cli#1]
``` bash
$ export JAVA_HOME=$(/usr/libexec/java_home)
$ gem install browsermob-cli
Fetching: addressable-2.4.0.gem (100%)
Successfully installed addressable-2.4.0
Fetching: thor-0.17.0.gem (100%)
Successfully installed thor-0.17.0
Fetching: browsermob-cli-0.1.4.gem (100%)
Successfully installed browsermob-cli-0.1.4
3 gems installed
$ browsermob-cli setup
<truncated>/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:121:in `require': cannot load such file -- browsermob/proxy (LoadError)
    from <truncated>/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:121:in `require'
    from <truncated>/.rvm/gems/ruby-2.1.2/gems/browsermob-cli-0.1.4/lib/browsermob/cli/browsermob.rb:2:in `<top (required)>'
    from <truncated>/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from <truncated>/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from <truncated>/.rvm/gems/ruby-2.1.2/gems/browsermob-cli-0.1.4/bin/browsermob-cli:6:in `<top (required)>'
    from <truncated>/.rvm/gems/ruby-2.1.2/bin/browsermob-cli:23:in `load'
  #...
```

**Comment by Shashikant86** [comment]
@samnissen Thanks a lot for reporting. I fixed 'run-time' dependencied in the latest vrsion however rack need ruby 2.2 or rubygem > 2.3 :(
